apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-app
data:
  index.html: |
    <html>
    <head>
      <title>Welcome to Nginx</title>
    </head>
    <body>
      <h1>Welcome to Nginx in Development Environment</h1>
    </body>
    </html>
